- name: Install Nginx
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: absent
        autoremove: yes
    # - name: stop Nginx
    #   ansible.builtin.service:
    #     name: nginx
    #     state: reloaded